### ISSUE TITLE
prepare use case and sequence diagrams

### ISSUE THREAD

**Issue by ozturkaslii** [communal-cloud/communal-cloud#12]
- use case: https://github.com/communal-cloud/communal-cloud/wiki/Use-Case-Diagrams
- sequence: https://github.com/communal-cloud/communal-cloud/wiki/Sequence-Diagrams
- class: https://github.com/communal-cloud/communal-cloud/wiki/Class-Diagram

**Comment by lkiran** [comment]
https://github.com/communal-cloud/communal-cloud/wiki/Class-Diagram
