### ISSUE TITLE
Prepare Requirements Document

### ISSUE THREAD

**Issue by mehmetyildi** [communal-cloud/communal-cloud#2]
All the developers will edit the requirement document on
https://docs.google.com/document/d/1IeMLsZS0Na0K308gf-VMHIeeKmloEXLPCyZSwrGUUc8/edit
The final will be presented to customer on Feb. 25th, 2019 at 19:00.

**Comment by lkiran** [comment]
Write missing requirements to requirements document @ozturkaslii @lkiran @yenerunver based on meeting topics,
@mehmetyildi based on the previous week in class discussion.
