### ISSUE TITLE
Register User

### ISSUE THREAD

**Issue by lkiran** [communal-cloud/communal-cloud#20]
+ Create user registration view
+  Validate form fields
    + name field must contain at least 3 characters
    + email must meet the following regex `^\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$`
    + password must be  meet the following regex `^(?=.*\d)(?=.*[\-\\*\'#$%&()[\]{}=+/!^])(?=.*[a-z])(?=.*[A-Z])(?!.*\s).{6,}$` _(Password must contain at least one of the -\*'#$%&()[]{}=+/!^ characters at least one small and capital letter and number)_
+ Submit a POST request to API /user/ to create user with body specified like the following example
```
{
	"email":"example@email.com",
	"username":"example@email.com",
	"name":"Name Surname",
	"password":"ExampleP@ssw0rd"
}
```

**Comment by cagrigunal** [comment]
validations are added
