### ISSUE TITLE
mobile app mockup design

### ISSUE THREAD

**Issue by lkiran** [communal-cloud/communal-cloud#9]
Work collaboratively and decide a graphical design tool to create project mockup. 

The mobile mockup design should include following pages, register page with steps, login, display workflow steps based on meeting discussions. Work collaboratively with webpage mockup designers.

Share your work on the wiki.

**Comment by Recreation34** [comment]
I started with mockplus tool, it has a 7 days trial but the price is to much (200USD), we can change the tool later.
